FROM python:3

ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# For the default command to run, it should run the intended Python file that you will create
CMD python attendees/account_info_consumer.py